export type Donation = {
  id: string;
  donorName: string;
  type: string;
  amount: number;
  method: string;
  campaign: string;
  fund: string;
  recurrence: string;
  source: string;
  matching: string;
  date: Date;
};

export const donors: Donation[] = [
  {
    id: "0",
    donorName: "Alice",
    type: "One-Time",
    amount: 150.75,
    method: "Credit Card",
    campaign: "Health",
    fund: "General",
    recurrence: "N/A",
    source: "Website",
    matching: "Yes",
    date: new Date("2024-07-15"),
  },
  {
    id: "1",
    donorName: "Bob",
    type: "Recurring",
    amount: 200.0,
    method: "Check",
    campaign: "Education",
    fund: "Scholarship",
    recurrence: "Monthly",
    source: "Social Media",
    matching: "no",
    date: new Date("2024-07-16"),
  },
  {
    id: "2",
    donorName: "Charlie",
    type: "Pledge",
    amount: 75.5,
    method: "Bank Transfer",
    campaign: "Food",
    fund: "Emergency Relief",
    recurrence: "Quarterly",
    source: "Event",
    matching: "yes",
    date: new Date("2024-07-17"),
  },
  {
    id: "3",
    donorName: "Diana",
    type: "Recurring",
    amount: 500.0,
    method: "Credit Card",
    campaign: "Health",
    fund: "Research",
    recurrence: "Monthly",
    source: "Email",
    matching: "yes",
    date: new Date("2024-07-18"),
  },
  {
    id: "4",
    donorName: "Evan",
    type: "In-Kind",
    amount: 100.0,
    method: "Cash",
    campaign: "Environment",
    fund: "Conservation",
    recurrence: "Annually",
    source: "Direct Mail",
    matching: "no",
    date: new Date("2024-07-19"),
  },
  {
    id: "5",
    donorName: "Fiona",
    type: "One-Time",
    amount: 250.5,
    method: "PayPal",
    campaign: "Community",
    fund: "Support Fund",
    recurrence: "N/A",
    source: "Referral",
    matching: "true",
    date: new Date("2024-07-20"),
  },
  {
    id: "6",
    donorName: "George",
    type: "Recurring",
    amount: 350.75,
    method: "ACH",
    campaign: "Education",
    fund: "Student Aid",
    recurrence: "Quarterly",
    source: "Social Media",
    matching: "no",
    date: new Date("2024-07-21"),
  },
  {
    id: "7",
    donorName: "Hannah",
    type: "Pledge",
    amount: 400.0,
    method: "Venmo",
    campaign: "Health",
    fund: "Wellness",
    recurrence: "Annually",
    source: "Website",
    matching: "yes",
    date: new Date("2024-07-22"),
  },
  {
    id: "8",
    donorName: "Isaac",
    type: "In-Kind",
    amount: 500.5,
    method: "Zelle",
    campaign: "Food",
    fund: "Food Bank",
    recurrence: "Monthly",
    source: "Event",
    matching: "no",
    date: new Date("2024-07-23"),
  },
  {
    id: "9",
    donorName: "Julia",
    type: "One-Time",
    amount: 600.0,
    method: "Check",
    campaign: "Environment",
    fund: "Reforestation",
    recurrence: "N/A",
    source: "Direct Mail",
    matching: "yes",
    date: new Date("2024-07-24"),
  },
];
