type Donation = {
  id: string;
  date: Date;
  category: string;
  amount: number | null;
  item: string | null;
  itemValue: number | null;
  paymentMethod: string | null;
  campaign: string;
  donorId: string;
  donor: {
    name: string;
  };
};

export const donors: Donation[] = [
  {
    id: "1",
    category: "Money",
    amount: 100,
    item: null,
    itemValue: null,
    paymentMethod: "Card",
    campaign: "Food",
    date: new Date("2024-01-01"),
    donorId: "1",
    donor: { name: "Bill" },
  },
  {
    id: "2",
    category: "Item",
    amount: null,
    item: "6 Backpacks",
    itemValue: 600,
    paymentMethod: null,
    campaign: "Backpack",
    date: new Date("2024-11-12"),
    donorId: "2",
    donor: { name: "Random Corp." },
  },
  {
    id: "3",
    category: "Item",
    amount: null,
    item: "2 Notebooks",
    itemValue: 4,
    paymentMethod: null,
    campaign: "Notebook",
    date: new Date("2024-01-12"),
    donorId: "2",
    donor: { name: "Random Corp." },
  },
  {
    id: "4",
    category: "Money",
    amount: 88.88,
    item: null,
    itemValue: null,
    paymentMethod: "Check",
    campaign: "Food",
    date: new Date("2024-01-01"),
    donorId: "1",
    donor: { name: "John" },
  },
  {
    id: "5",
    category: "Money",
    amount: 25.99,
    item: null,
    itemValue: null,
    paymentMethod: "Check",
    campaign: "Food",
    date: new Date("2024-01-01"),
    donorId: "1",
    donor: { name: "John" },
  },
  {
    id: "6",
    category: "Item",
    amount: null,
    item: "10 Books",
    itemValue: 150,
    paymentMethod: null,
    campaign: "Library",
    date: new Date("2024-05-10"),
    donorId: "3",
    donor: { name: "Alice" },
  },
  {
    id: "7",
    category: "Money",
    amount: 50.5,
    item: null,
    itemValue: null,
    paymentMethod: "PayPal",
    campaign: "Wellness",
    date: new Date("2024-02-20"),
    donorId: "4",
    donor: { name: "Tom" },
  },
  {
    id: "8",
    category: "Item",
    amount: null,
    item: "5 Computers",
    itemValue: 2000,
    paymentMethod: null,
    campaign: "Upgrade",
    date: new Date("2024-09-01"),
    donorId: "5",
    donor: { name: "Tech Co." },
  },
  {
    id: "9",
    category: "Money",
    amount: 120.75,
    item: null,
    itemValue: null,
    paymentMethod: "Wire Transfer",
    campaign: "Scholarship",
    date: new Date("2024-03-15"),
    donorId: "6",
    donor: { name: "Sarah" },
  },
  {
    id: "10",
    category: "Money",
    amount: 300,
    item: null,
    itemValue: null,
    paymentMethod: "Card",
    campaign: "Vaccination",
    date: new Date("2024-07-07"),
    donorId: "7",
    donor: { name: "Mike" },
  },
  {
    id: "11",
    category: "Item",
    amount: null,
    item: "20 Pencils",
    itemValue: 10,
    paymentMethod: null,
    campaign: "Supplies",
    date: new Date("2024-08-12"),
    donorId: "8",
    donor: { name: "Bob" },
  },
  {
    id: "12",
    category: "Money",
    amount: 45.99,
    item: null,
    itemValue: null,
    paymentMethod: "Check",
    campaign: "Clean-Up",
    date: new Date("2024-06-18"),
    donorId: "9",
    donor: { name: "Green Org." },
  },
  {
    id: "13",
    category: "Item",
    amount: null,
    item: "3 Laptops",
    itemValue: 1800,
    paymentMethod: null,
    campaign: "Upgrade",
    date: new Date("2024-10-10"),
    donorId: "10",
    donor: { name: "Innovative Solutions" },
  },
  {
    id: "14",
    category: "Money",
    amount: 200,
    item: null,
    itemValue: null,
    paymentMethod: "Cash",
    campaign: "Research",
    date: new Date("2024-04-22"),
    donorId: "11",
    donor: { name: "Rachel" },
  },
  {
    id: "15",
    category: "Item",
    amount: null,
    item: "5 Chairs",
    itemValue: 250,
    paymentMethod: null,
    campaign: "Classroom",
    date: new Date("2024-12-01"),
    donorId: "12",
    donor: { name: "Furniture Co." },
  },
  {
    id: "16",
    category: "Money",
    amount: 75,
    item: null,
    itemValue: null,
    paymentMethod: "Debit Card",
    campaign: "Team Gear",
    date: new Date("2024-05-25"),
    donorId: "13",
    donor: { name: "Jim" },
  },
  {
    id: "17",
    category: "Item",
    amount: null,
    item: "4 Sports Balls",
    itemValue: 80,
    paymentMethod: null,
    campaign: "Equipment",
    date: new Date("2024-06-30"),
    donorId: "14",
    donor: { name: "Local Sports Shop" },
  },
  {
    id: "18",
    category: "Money",
    amount: 150.25,
    item: null,
    itemValue: null,
    paymentMethod: "Bank Transfer",
    campaign: "Exhibition",
    date: new Date("2024-02-14"),
    donorId: "15",
    donor: { name: "Art Lovers" },
  },
  {
    id: "19",
    category: "Item",
    amount: null,
    item: "15 Paint Brushes",
    itemValue: 35,
    paymentMethod: null,
    campaign: "Supplies",
    date: new Date("2024-08-21"),
    donorId: "16",
    donor: { name: "Creative Supplies" },
  },
  {
    id: "20",
    category: "Money",
    amount: 500,
    item: null,
    itemValue: null,
    paymentMethod: "Check",
    campaign: "Medical Aid",
    date: new Date("2024-03-30"),
    donorId: "17",
    donor: { name: "Health Foundation" },
  },
];
